FROM python:3.12.0

WORKDIR /app

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# install psycopg2 dependencies
# RUN apt-get update \
#     && apt-get add postgresql-dev gcc python3-dev musl-dev
RUN apt-get update && \
    apt-get install -y libpq-dev gcc

# Install dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy project
COPY ./ .

EXPOSE 8000

# CMD ["python", "./manage.py", "runserver", "0.0.0.0:8000"]